# Generated by Django 5.2.8 on 2025-12-02 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('data_inicio_contrato', models.DateField(blank=True, null=True, verbose_name='Início do Contrato')),
                ('data_finalizacao_contrato', models.DateField(blank=True, null=True, verbose_name='Fim do Contrato')),
                ('nome_representante', models.CharField(blank=True, max_length=255, verbose_name='Nome do Representante')),
                ('celular_representante', models.CharField(blank=True, max_length=20, verbose_name='Celular do Representante')),
                ('email_representante', models.EmailField(blank=True, max_length=254, verbose_name='Email do Representante')),
                ('anexo_contrato', models.FileField(blank=True, null=True, upload_to='contratos/', verbose_name='Anexo do Contrato')),
                ('manual_marca', models.FileField(blank=True, null=True, upload_to='manual/', verbose_name='Anexo do Manual da Marca')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_clientes/', verbose_name='Logo do Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Projeto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('pausado', 'Pausado')], default='em_andamento', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.client')),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('x', 'X (Twitter)'), ('threads', 'Threads')], max_length=20)),
                ('account_name', models.CharField(max_length=255, verbose_name='Nome da Conta')),
                ('account_id', models.CharField(max_length=255, verbose_name='ID na Rede Social')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='projects.client')),
            ],
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True, verbose_name='Legenda/Copy')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='social_posts/', verbose_name='Imagem/Vídeo')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Agendamento')),
                ('approval_status', models.CharField(choices=[('draft', 'Rascunho'), ('copy_review', 'Aprovação: Copy'), ('design_review', 'Aprovação: Design'), ('internal_approval', 'Aprovação Interna'), ('client_approval', 'Aprovação Cliente'), ('approved_to_schedule', 'Pronto para Agendar')], default='draft', max_length=30, verbose_name='Status de Aprovação')),
                ('approval_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('feedback_text', models.TextField(blank=True, null=True, verbose_name='Motivo Reprova (Texto)')),
                ('feedback_image_markup', models.TextField(blank=True, null=True, verbose_name='Rabisco na Imagem (Base64)')),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='projects.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialPostDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_type', models.CharField(choices=[('feed', 'Feed (Quadrado/Retrato)'), ('story', 'Story (Vertical)'), ('reel', 'Reels/Shorts (Vertical)'), ('video', 'Vídeo Horizontal'), ('text', 'Apenas Texto')], default='feed', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.socialaccount')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.socialpost')),
            ],
        ),
        migrations.AddField(
            model_name='socialpost',
            name='accounts',
            field=models.ManyToManyField(related_name='posts', through='projects.SocialPostDestination', to='projects.socialaccount'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanban_type', models.CharField(choices=[('general', 'Geral'), ('operational', 'Operacional')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('todo', 'A Fazer'), ('doing', 'Em Andamento'), ('done', 'Concluído'), ('briefing', 'Briefing'), ('copy', 'Copy'), ('design', 'Design'), ('internal_approval', 'Aprovação Interna'), ('client_approval', 'Aprovação Cliente'), ('scheduling', 'Agendamento'), ('published', 'Publicado')], default='todo', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído a')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
                ('social_post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='projects.socialpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
