# Generated by Django 5.2.8 on 2025-12-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpostdestination',
            name='format_type',
            field=models.CharField(choices=[('facebook_feed', 'Facebook - Feed'), ('facebook_story', 'Facebook - Story'), ('instagram_feed', 'Instagram - Feed'), ('instagram_story', 'Instagram - Story'), ('instagram_reel', 'Instagram - Reels'), ('threads_post', 'Threads'), ('youtube_video', 'YouTube - Vídeo Longo'), ('youtube_short', 'YouTube - Shorts'), ('tiktok_post', 'TikTok'), ('linkedin_feed', 'LinkedIn'), ('x_post', 'X (Twitter)'), ('pinterest_pin', 'Pinterest')], max_length=50),
        ),
    ]
