# Generated by Django 5.2.8 on 2025-12-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='platforms_config',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
