# Generated by Django 5.2.8 on 2025-12-06 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_task_social_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='social_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='projects.socialpost'),
        ),
    ]
