# Generated by Django 5.2.8 on 2025-12-06 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_task_social_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='social_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_link', to='projects.socialpost'),
        ),
    ]
