# Generated by Django 5.2.8 on 2025-12-08 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_task_social_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='projects.client', verbose_name='Cliente Vinculado'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('youtube', 'YouTube'), ('threads', 'Threads'), ('x', 'X (Twitter)'), ('tiktok_ads', 'TikTok Ads'), ('linkedin_ads', 'LinkedIn Ads'), ('meta_ads', 'Meta Ads'), ('google_ads', 'Google Ads'), ('google_my_business', 'Google Meu Negócio'), ('ga4', 'Google Analytics 4')], max_length=50),
        ),
    ]
