# Generated by Django 5.2.8 on 2025-12-31 05:41

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_domain_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('data_inicio_contrato', models.DateField(blank=True, null=True, verbose_name='Início do Contrato')),
                ('data_finalizacao_contrato', models.DateField(blank=True, null=True, verbose_name='Fim do Contrato')),
                ('nome_representante', models.CharField(blank=True, max_length=255, verbose_name='Nome do Representante')),
                ('celular_representante', models.CharField(blank=True, max_length=20, verbose_name='Celular do Representante')),
                ('email_representante', models.EmailField(blank=True, max_length=254, verbose_name='Email do Representante')),
                ('anexo_contrato', models.FileField(blank=True, null=True, upload_to='contratos/', verbose_name='Anexo do Contrato')),
                ('manual_marca', models.FileField(blank=True, null=True, upload_to='manual/', verbose_name='Anexo do Manual da Marca')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_clientes/', verbose_name='Logo do Cliente')),
                ('is_active', models.BooleanField(default=True, verbose_name='Cliente Ativo?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_domains', to='accounts.agency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
