# Generated by Django 5.2.8 on 2026-01-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor'), ('viewer', 'Visualizador')], default='viewer', max_length=20, verbose_name='Função'),
        ),
    ]
