"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'app.brainzhub.com.br',
    'brainz.localhost', 
    'tenant2.localhost', 
    'tenant1.localhost', 
    'localhost', 
    '127.0.0.1',
    'randolph-governable-ayana.ngrok-free.dev',
    '.ngrok-free.app',
    '31.97.175.182',
    '*',
    ]

CSRF_TRUSTED_ORIGINS = [
    'https://randolph-governable-ayana.ngrok-free.dev',
]

# Application definition

SHARED_APPS = [
    'django_tenants',
    #'tenants',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
]

TENANT_APPS = [
    'django.contrib.contenttypes', 
    'django.contrib.auth',
    'projects',
]

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

TENANT_MODEL = "accounts.Agency" 
TENANT_DOMAIN_MODEL = "accounts.Domain"

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.agency_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend', 
        
        # CORREÇÃO: Use os nomes exatos do .env
        'NAME': config('DATABASE_NAME'),
        'USER': config('DATABASE_USER'),
        'PASSWORD': config('DATABASE_PASSWORD'), 
        'HOST': config('DATABASE_HOST'),
        'PORT': config('DATABASE_PORT'),
    }
}

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

ROOT_URLCONF = 'config.urls'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

AUTH_USER_MODEL = 'accounts.CustomUser'

# config/settings.py

# Para onde o Django redireciona *depois* do login
LOGIN_REDIRECT_URL = 'dashboard'

# Qual é a URL da nossa página de login
LOGIN_URL = 'login'

# Qual é a URL da nossa página de logout
LOGOUT_REDIRECT_URL = 'login'

# Configurações de Mídia
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configurações da API do Google
GOOGLE_OAUTH_CLIENT_ID = config('GOOGLE_OAUTH_CLIENT_ID')
GOOGLE_OAUTH_CLIENT_SECRET = config('GOOGLE_OAUTH_CLIENT_SECRET')

# A URL de retorno que você configurou no Google
GOOGLE_OAUTH_REDIRECT_URI = "http://localhost:8000/google-auth-callback/"

# Os escopos que estamos solicitando
GOOGLE_OAUTH_SCOPES = [
    "https://www.googleapis.com/auth/calendar.events",
    "https://www.googleapis.com/auth/userinfo.profile",
    "https://www.googleapis.com/auth/userinfo.email",
    "openid",
]

# Para desenvolvimento, imprime e-mails no console em vez de enviá-los.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# META API
META_APP_ID = config('META_APP_ID')
META_APP_SECRET = config('META_APP_SECRET')
META_REDIRECT_URI = config('META_REDIRECT_URI')

# Escopos (Permissões) que vamos pedir
# Precisamos de permissão para ler páginas, publicar posts e ler insights
META_SCOPES = [
    'email',
    'public_profile',
    'pages_show_list',
    'pages_read_engagement',
    'pages_manage_posts',
    'pages_read_user_content',
    'instagram_basic',
    'instagram_content_publish',
    'instagram_manage_insights',
    # 'business_management' 
]

# LINKEDIN API
LINKEDIN_CLIENT_ID = config('LINKEDIN_CLIENT_ID')
LINKEDIN_CLIENT_SECRET = config('LINKEDIN_CLIENT_SECRET')
LINKEDIN_REDIRECT_URI = config('LINKEDIN_REDIRECT_URI')
LINKEDIN_SCOPES = ['openid', 'profile', 'email', 'w_member_social']

# TIKTOK SETTINGS
TIKTOK_CLIENT_KEY = config('TIKTOK_CLIENT_KEY')
TIKTOK_CLIENT_SECRET = config('TIKTOK_CLIENT_SECRET')
TIKTOK_REDIRECT_URI = config('TIKTOK_REDIRECT_URI')


# --- CONFIGURAÇÕES DE PROXY (Obrigatório para EasyPanel) ---
# Diz ao Django para confiar no cabeçalho Host que o EasyPanel envia
USE_X_FORWARDED_HOST = True
# Diz ao Django que a conexão é segura (HTTPS)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# --- DEBUG DE TENANTS ---
# Se o domínio não for encontrado, exibe o site público em vez de 404.
# Isso vai nos provar se o erro é de domínio ou de rota.
SHOW_PUBLIC_IF_NO_TENANT_FOUND = True
